#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app=$1
app_dir=$PLUSHU_APPS_DIR/$app
iidfile=$app_dir/release.iid

# remove the current release image
if [[ -f "$iidfile" ]]; then
  docker rmi --no-prune "$(<"$iidfile")" > /dev/null
  rm "$iidfile"
fi
